language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-30.0.1

    # The SDK version used to compile your project
    - android-28

licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
    - chmod +x gradlew

script:
    - ./gradlew clean jacocoTestReport

after_success: 
    - bash <(curl -s https://codecov.io/bash)
