language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools

licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
    - chmod +x gradlew
    - yes | sdkmanager "platforms;android-29"
    - yes | sdkmanager "build-tools;29.0.2"

script:
    - ./gradlew clean jacocoTestReport

after_success: 
    - bash <(curl -s https://codecov.io/bash)
